/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carreracaballos;
//importar librerias
import javax.swing.JLabel;

/**
 *
 * @author santi
 */
public class frmCarreraCaballos extends javax.swing.JFrame {

    /**
     * Creates new form frmCarreraCaballos
     */
    //Aplicar los getters para retornar el label de cada caballo para los movimientos
    public frmCarreraCaballos() {
        initComponents();
    }

    public JLabel getlblCaballo1() {
        return lblCaballo1;
    }

    public JLabel getlblCaballo2() {
        return lblCaballo2;
    }

    public JLabel getlblCaballo3() {
        return lblCaballo3;
    }

    public JLabel getlblCaballo4() {
        return lblCaballo4;
    }

    public JLabel getlblCaballo5() {
        return lblCaballo5;
    }

    public JLabel getlblCaballo6() {
        return lblCaballo6;
    }
    
    public JLabel getlblCaballo7() {
        return lblCaballo7;
    }

    public JLabel getlblCaballo8() {
        return lblCaballo8;
    }

    public JLabel getlblCaballo9() {
        return lblCaballo9;
    }
    
     public JLabel getlblCaballo10() {
        return lblCaballo10;
    }
     
    public JLabel getlblMeta() {
        return lblMeta;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblMeta = new javax.swing.JLabel();
        lblCaballo1 = new javax.swing.JLabel();
        lblCaballo2 = new javax.swing.JLabel();
        lblCaballo3 = new javax.swing.JLabel();
        lblCaballo4 = new javax.swing.JLabel();
        lblCaballo5 = new javax.swing.JLabel();
        lblCaballo6 = new javax.swing.JLabel();
        lblCaballo7 = new javax.swing.JLabel();
        lblCaballo8 = new javax.swing.JLabel();
        lblCaballo9 = new javax.swing.JLabel();
        lblCaballo10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblMeta.setBackground(new java.awt.Color(204, 0, 0));
        lblMeta.setIcon(new javax.swing.ImageIcon("C:\\Users\\tatan\\Desktop\\343-meta_400px.jpg")); // NOI18N

        lblCaballo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carreracaballos/587172f57b7f6103e35c6cc1_2.png"))); // NOI18N

        lblCaballo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carreracaballos/587172f57b7f6103e35c6cc1_2.png"))); // NOI18N

        lblCaballo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carreracaballos/587172f57b7f6103e35c6cc1_2.png"))); // NOI18N

        lblCaballo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carreracaballos/587172f57b7f6103e35c6cc1_2.png"))); // NOI18N

        lblCaballo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carreracaballos/587172f57b7f6103e35c6cc1_2.png"))); // NOI18N

        lblCaballo6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carreracaballos/587172f57b7f6103e35c6cc1_2.png"))); // NOI18N

        lblCaballo7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carreracaballos/587172f57b7f6103e35c6cc1_2.png"))); // NOI18N

        lblCaballo8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carreracaballos/587172f57b7f6103e35c6cc1_2.png"))); // NOI18N

        lblCaballo9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carreracaballos/587172f57b7f6103e35c6cc1_2.png"))); // NOI18N

        lblCaballo10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carreracaballos/587172f57b7f6103e35c6cc1_2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblCaballo1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(lblCaballo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCaballo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCaballo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCaballo7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCaballo8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCaballo9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCaballo5))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(lblCaballo10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(367, 367, 367))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCaballo6)
                        .addGap(600, 600, 600)))
                .addComponent(lblMeta, javax.swing.GroupLayout.PREFERRED_SIZE, 60, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblCaballo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCaballo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCaballo3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCaballo4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCaballo5)
                        .addGap(18, 18, 18)
                        .addComponent(lblCaballo6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCaballo7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCaballo8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCaballo9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(lblMeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(lblCaballo10)
                .addGap(302, 302, 302))
        );

        jLabel1.setText("CARRERA DE CABALLOS");

        jButton1.setText("EMPEZAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel1)
                        .addGap(0, 1215, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(219, 219, 219)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Hacer que todos los caballos inicien desde la misma poscion en y
        lblCaballo1.setLocation(0, lblCaballo1.getLocation().y);
        lblCaballo2.setLocation(0, lblCaballo2.getLocation().y);
        lblCaballo3.setLocation(0, lblCaballo3.getLocation().y);
        lblCaballo4.setLocation(0, lblCaballo4.getLocation().y);
        lblCaballo5.setLocation(0, lblCaballo5.getLocation().y);
        lblCaballo6.setLocation(0, lblCaballo6.getLocation().y);
        lblCaballo7.setLocation(0, lblCaballo7.getLocation().y);
        lblCaballo8.setLocation(0, lblCaballo8.getLocation().y);
        lblCaballo9.setLocation(0, lblCaballo9.getLocation().y);
        lblCaballo10.setLocation(0, lblCaballo10.getLocation().y);
        Carrera hilo1 = new Carrera(lblCaballo1, this);
        Carrera hilo2 = new Carrera(lblCaballo2, this);
        Carrera hilo3 = new Carrera(lblCaballo3, this);
        Carrera hilo4 = new Carrera(lblCaballo4, this);
        Carrera hilo5 = new Carrera(lblCaballo5, this);
        Carrera hilo6 = new Carrera(lblCaballo6, this);
        Carrera hilo7 = new Carrera(lblCaballo7, this);
        Carrera hilo8 = new Carrera(lblCaballo8, this);
        Carrera hilo9 = new Carrera(lblCaballo9, this);
        Carrera hilo10 = new Carrera(lblCaballo10, this);
        
        //Inicio de carrera
        hilo1.start();
        hilo2.start();
        hilo3.start();
        hilo4.start();
        hilo5.start();
        hilo6.start();
        hilo7.start();
        hilo8.start();
        hilo9.start();
        hilo10.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCarreraCaballos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCarreraCaballos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCarreraCaballos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCarreraCaballos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCarreraCaballos().setVisible(true);// Que sea visible la carrera
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblCaballo1;
    private javax.swing.JLabel lblCaballo10;
    private javax.swing.JLabel lblCaballo2;
    private javax.swing.JLabel lblCaballo3;
    private javax.swing.JLabel lblCaballo4;
    private javax.swing.JLabel lblCaballo5;
    private javax.swing.JLabel lblCaballo6;
    private javax.swing.JLabel lblCaballo7;
    private javax.swing.JLabel lblCaballo8;
    private javax.swing.JLabel lblCaballo9;
    private javax.swing.JLabel lblMeta;
    // End of variables declaration//GEN-END:variables
}
